### ISSUE TITLE
CMake overwrites CMAKE_SYSTEM_PROCESSOR when not explicitly cross-compiling

### ISSUE THREAD

**Issue by jofa-ph** [IARSystems/cmake-tutorial#20]
CMake overwrites `CMAKE_SYSTEM_PROCESSOR` which is set in [iar-toolchain.cmake](https://github.com/IARSystems/cmake-tutorial/blob/master/examples/iar-toolchain.cmake) with detected PC architecture (e.g. AMD64). Therefore, the CSpy tests created using the function `iar_cspy_add_test` defined in [iar-cspy-rl78.cmake](https://github.com/IARSystems/cmake-tutorial/blob/master/examples/rl78/iar-cspy-rl78.cmake) fail. This is, because file names are created using the overwritten variable.

To fix this, `CMAKE_SYSTEM_NAME` should be set to `Generic` in the toolchain file. This keeps CMake from automatically detecting and overwriting `CMAKE_SYSTEM_PROCESSOR`.

**Comment by felipe-iar** [comment]
Thanks for reporting this bug, Jonas. We will get it fixed soon.
