### ISSUE TITLE
能否提供更复杂的cmake例子？

### ISSUE THREAD

**Issue by 791314247** [IARSystems/cmake-tutorial#28]
目前hello-world的cmake太简单了，能否提供更复杂的例子，比如自动搜索源文件构建工程等

**Comment by felipe-iar** [comment]
Your Mandarin is too advanced for me! :-) After applying machine translation...

Thanks for your suggestion. 

>This tutorial serves as __a very basic-level guide__ to using CMake together with the IAR C/C++ compilers to cross-compile embedded software applications for the supported target architectures.

The "hello-world" was added exactly for the opposite reason you are now suggesting. Earlier, the provided examples were not so clear about what a "minimal" project would be.

In the end, it is an open-ended tutorial, and our aim is not to go too deep into all options CMake offers. That would be for the CMake's official documentation (and books). If you are already aware of `FILE_GLOB` possibilities and wants use that on your own projects, please be aware of the consequences. `FILE_GLOB` for blindly adds sources to a target, the CMake developers themselves advocate against its use as it will, in the best case, hide dependencies if not worse. It is explained in the documentation's first [note](https://cmake.org/cmake/help/latest/command/file.html?file#filesystem:~:text=the%20build%20system.-,Note,-We%20do%20not).

Please also consider [Effective Modern CMake](https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1), a collection of hints and best practices for your projects.

**Comment by 791314247** [comment]
ok, thk
