### ISSUE TITLE
Suggestion - Example with Trustzone (one NS project ans one S project) enabled

### ISSUE THREAD

**Issue by bastien-sagetat** [IARSystems/cmake-tutorial#37]
It would be great to have an example with the ARM TrustZone enabled, which would generate 2 binaries/projects, a non-secure project and a secure project.

**Comment by felipe-iar** [comment]
Hi @bastien-sagetat 

Thank you very much for your suggestion. It is indeed an interesting one!

Did you face any specific problem when engaging with a CMake project as such?

**Comment by felipe-iar** [comment]
Fixed in #38.

**Comment by bastien-sagetat** [comment]
Not really, but we will need to implement such a makefile in a near future.

**Comment by bastien-sagetat** [comment]
Thanks for the update ! Was quite fast.

**Comment by felipe-iar** [comment]
Excellent! Thanks. Whenever possible, please try it out, let us know how it goes and, of course, reach out in case there are questions.

**Comment by felipe-iar** [comment]
Closing this due inactivity. Please feel free to reach out to us for further discussions!
