### ISSUE TITLE
VS code - CMake - Ubuntu tutorial missing

### ISSUE THREAD

**Issue by hoditohod** [iarsystems/cmake-tutorial#41]
Loosely connected but: I'm trying to set up a linux dev environment with IAR, and yesterday I bumped into a nice summary by Felipe, that's gone by today and unfortunately I haven't cloned it. Is it possible to access this tutorial somehow? Will it be included in under iarsystems tutorial collection?

It was here: https://github.com/felipe-iar/iar-vscode-cmake-ubuntu

Thanks in advance!

**Comment by felipe-iar** [comment]
It's here now! https://github.com/iarsystems/cmake-tutorial/wiki/Building-and-Debugging-from-Visual-Studio-Code-(Linux)

**Comment by hoditohod** [comment]
Cool, thanks!

**Comment by felipe-iar** [comment]
Thanks for your interest! @hoditohod  Feel free to reach out for further details!
