### ISSUE TITLE
Debug the .elf file, enter the abort  

### ISSUE THREAD

**Issue by zhaoGilbert** [IARSystems/cmake-tutorial#8]
[](url)After generating an elf file, I enter debug and cannot run to _main,
If after entering abnormal inter
[CMakeLists.txt](https://github.com/IARSystems/cmake-tutorial/files/8061414/CMakeLists.txt)
rupt。

**Comment by felipe-iar** [comment]
It seems your project builds fine and then the application never reaches `main()`. This question beyond the [cmake-tutorial](https://github.com/iarsystems/cmake-tutorial).
I'd advise you contact the IAR Systems Technical Support (https://www.iar.com/rfta) directly if you need further assistance.

I will close now this issue.
